spring:
  application:
    name: service-route
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-consumer
    api-b:
      path: /api-b/**
      serviceId: service-consumer